# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joy Buongiorno, PhD
email: JBuongiorno@carnegiescience.edu
description: > # this means to ignore newlines until "baseurl:"
  Joy Buongiorno
baseurl: ""
url: "https://jbuongio.github.io/"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Post configurator
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true

# Site Footer
footer:
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jbuongiorno@carnegiescience.edu"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DrJoyBuongiorno"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jbuongio"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=3pa76GEAAAAJ&hl=en&oi=ao"
      
future: true
